name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # cada 5 minutos (UTC)
  workflow_dispatch:        # puedes lanzarlo a mano

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -sS -m 10 https://web-evermountsolutions-3.onrender.com || true
